# Assorted Demonstrations
This example contains some nuances of Pandas that are well worth knowing about, but not essential to a working understanding of the topic.   Details are drawn out in the notes following the script.

## Trig Functions, Lambdas and NaN

In [1]:
#Import the NumPy math library
import numpy as np
import pandas as pd

#Create data for the angles around a circle in 45 degree increments
deg = [angle/1 for angle in range(0, 361, 45)]  # a list comprehension

#Make a DataFrame using the angles its first column
df = pd.DataFrame(data = deg, columns=['deg'])

#Make another column for radians (that's how NumPy thinks about angles).
df['rad'] = df['deg'].apply(np.math.radians)

#Now create a few trig columns
df['sin'] = np.sin(df['rad'])
df['cos'] = np.cos(df['rad'])
df['tan'] = np.tan(df['rad'])
df['arcsin'] = np.arcsin(df['rad'])
df['arccos'] = np.arccos(df['rad'])
df['arctan'] = np.arctan(df['rad'])

df['tan'] = df['tan'].apply(lambda x: np.inf if x > 1e3 else x)
df = df.astype(float)

#Change values to floats and knock down the display precision
df = df.astype(float)
pd.options.display.float_format = '{:,.2f}'.format

df

c:\Anaconda\envs\py37\lib\site-packages\pandas\core\series.py:853: RuntimeWarning: invalid value encountered in arcsin
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Anaconda\envs\py37\lib\site-packages\pandas\core\series.py:853: RuntimeWarning: invalid value encountered in arccos
  result = getattr(ufunc, method)(*inputs, **kwargs)

     deg  rad   sin   cos   tan  arcsin  arccos  arctan
0   0.00 0.00  0.00  1.00  0.00    0.00    1.57    0.00
1  45.00 0.79  0.71  0.71  1.00    0.90    0.67    0.67
2  90.00 1.57  1.00  0.00   inf     nan     nan    1.00
3 135.00 2.36  0.71 -0.71 -1.00     nan     nan    1.17
4 180.00 3.14  0.00 -1.00 -0.00     nan     nan    1.26
5 225.00 3.93 -0.71 -0.71  1.00     nan     nan    1.32
6 270.00 4.71 -1.00 -0.00   inf     nan     nan    1.36
7 315.00 5.50 -0.71  0.71 -1.00     nan     nan    1.39
8 360.00 6.28 -0.00  1.00 -0.00     nan     nan    1.41

- Warnings:  you may notice that warnings about not-calculated values pop up the first time you run this script, but not later.   This behavior can be addressed by including the following code:

        import warnings
        warnings.filterwarnings('ignore')  #'always' is another option

- The apply() method can be used to implement a function against every cell of a data column (Series object) - or even the entire DataFrame.  You just need to specify the full name of the function:

        df['rad'] = df['deg'].apply(np.math.radians)
        
- In Python you can "roll you own" ad hoc functions by implementing them as anonymous lambda functions.  This works well for simple, self-explanitory operations because it keeps the code geographically local and easy to audit.  This function applys a NumPy placeholder value for an infinite value.

        df['tan'] = df['tan'].apply(lambda x: np.inf if x > 1e3 else x)
        
- Here is an alternative way to format output.  It uses the syntax from Python's mini-formatting language (which can give you really granular control).  This specific example formats floating point numbers only, with 2 decimal points of precision, using a comma separator for large values:

        pd.options.display.float_format = '{:,.2f}'.format
        
- Here is a list comprension to whip up a Python list object.  The surrounding [square brackets] signal that you want a list.  The first bit "angle/1" specifies what will be inside.  Dividing by one is an easy way to force the contents to be floating point numbers.  The "range(0, 361, 45)" part is an iterable object that produces 0, then keeps adding 45 until it gets past 360.

        deg = [angle/1 for angle in range(0, 361, 45)] 
        
- ... the simplest syntax is: [ list_element for index in iterable_object ]